Wayland: clean up services.
Complete Void migration, fix exec-if-exist.

diff --git a/utils/.local/bin/exec-if-exists b/utils/.local/bin/exec-if-exists
--- a/utils/.local/bin/exec-if-exists
+++ b/utils/.local/bin/exec-if-exists
@@ -1,7 +1,14 @@
 #!/bin/sh
 
-[ -r "$1" ] && exec "$@" 2>&1
+set -e
 
-# if EXISTFAIL is set, exit, otherwise sleep
-[ -z "$EXISTFAIL" ] && exit 1
-exec sleep 999
+if command -v "$1" >/dev/null; then
+    exec "$@" 2>&1
+else
+    echo "$1 not found"
+    if [ -n "$NOEXISTFAIL" ]; then
+        exit 1
+    else
+        exec sleep 999
+    fi
+fi
